server:
  port: '8083'

spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp
    password: Shimpi@09
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true   '
welcome:
  message: Welcome TO Spring Boot !!

management:
  endpoints:
    web:
      exposure:
        include: "*"
---
spring:
  profiles: qa
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp-qa
    password: Shimpi@09
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true   '
welcome:
  message: Welcome TO Spring Boot !!
---
spring:
  profiles: prod
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp-prod
    password: Shimpi@09
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true   '
welcome:
  message: Welcome TO Spring Boot !!